### ISSUE TITLE
[BUG]: Block application failed after finalization (at height 1444139)

### ISSUE THREAD

**Issue by motoeng** [koinos/koinos#49] opened 2022-10-18 13:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This node is new and was started and has not been shut down.
git checkout v0.4.1 
docker compose --profile all up

Node failed to sync.

Logs attached. 

[koinos node logs.zip](https://github.com/koinos/koinos/files/9810709/koinos.node.logs.zip)

### Environment

```markdown
- OS:
Ubuntu 20.04 LTS 
VPS on Digital Ocean
4vCPUs
8GB RAM
```

**Comment by mvandeberg** [comment] 2022-10-19 23:20
Duplicate of koinos/koinos-state-db-cpp#1

**Closed by mvandeberg** 2022-10-19 23:21 UTC
Labels: bug
